version: '3.8'
services:
  postgres:
    image: postgres:10.3
    restart: always
    environment:
      - POSTGRES_DB=financeiro
      - POSTGRES_USER=techtitans
      - POSTGRES_PASSWORD=180624
    volumes:
      - postgres:/var/lib/postgresql/data
    ports:
      - '5432:5432'
volumes:
  postgres: